from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '504f3f010cf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('uuid', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('chat_type', sa.Enum('PERSONAL', 'GROUP', 'CHANNEL', 'DEFAULT', name='chattype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index('idx_chats_type', ['chat_type'], unique=False)

    op.create_table('media',
    sa.Column('uuid', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_hash'), ['hash'], unique=True)

    op.create_table('users',
    sa.Column('uuid', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('phone_number_encrypted', sa.String(length=512), nullable=True),
    sa.Column('phone_number_hash', sa.String(length=64), nullable=True),
    sa.Column('phone_number_mask', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number_hash'), ['phone_number_hash'], unique=False)

    op.create_table('messages',
    sa.Column('uuid', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_extra_data', sa.Boolean(), nullable=False),
    sa.Column('chat_uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['chat_uuid'], ['chats.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_chat_created', ['chat_uuid', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_chat_uuid'), ['chat_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_uuid'), ['user_uuid'], unique=False)

    op.create_table('participants',
    sa.Column('uuid', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_uuid', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('resource_uuid', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('resource_type', sa.Enum('CHAT', 'MESSAGE', 'FILE', 'CHANNEL', name='resourcetype'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index('idx_participant_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_participant_permissions', ['permissions'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_participant_resource_type_uuid', ['resource_type', 'resource_uuid'], unique=False)
        batch_op.create_index('idx_participant_unique', ['user_uuid', 'resource_uuid', 'resource_type'], unique=True)
        batch_op.create_index('idx_participant_user_resource', ['user_uuid', 'resource_uuid'], unique=False)
        batch_op.create_index('idx_participant_user_resource_type', ['user_uuid', 'resource_type', 'resource_uuid'], unique=False)

    op.create_table('profile_custom',
    sa.Column('uuid', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=67), nullable=False),
    sa.Column('avatar_url', sa.String(length=555), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('profile_custom', schema=None) as batch_op:
        batch_op.create_index('idx_profile_custom_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('idx_profile_custom_user_uuid', ['user_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_custom_user_uuid'), ['user_uuid'], unique=False)

    op.create_table('message_data',
    sa.Column('message_uuid', sa.String(length=36), nullable=False),
    sa.Column('extra_data_type', sa.Enum('poll', 'inline_keyboard', 'reactions', 'embed', 'custom', 'media', name='extra_data_type'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_uuid'], ['messages.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_uuid')
    )
    with op.batch_alter_table('message_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_data_extra_data_type'), ['extra_data_type'], unique=False)

    op.create_table('message_reference',
    sa.Column('uuid', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('reference_type', sa.Enum('answer', 'remember', 'quote', name='reference_type'), nullable=False),
    sa.Column('source_uuid', sa.String(length=36), nullable=False),
    sa.Column('target_uuid', sa.String(length=36), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('span_all', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_uuid'], ['messages.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_uuid'], ['messages.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('message_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reference_source_uuid'), ['source_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reference_target_uuid'), ['target_uuid'], unique=False)
        batch_op.create_index('ix_msg_ref_target_type', ['target_uuid', 'reference_type'], unique=False)
        batch_op.create_index('uq_msg_ref_source_type', ['source_uuid', 'reference_type'], unique=True, postgresql_where=sa.text("reference_type IN ('answer', 'quote')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_reference', schema=None) as batch_op:
        batch_op.drop_index('uq_msg_ref_source_type', postgresql_where=sa.text("reference_type IN ('answer', 'quote')"))
        batch_op.drop_index('ix_msg_ref_target_type')
        batch_op.drop_index(batch_op.f('ix_message_reference_target_uuid'))
        batch_op.drop_index(batch_op.f('ix_message_reference_source_uuid'))

    op.drop_table('message_reference')
    with op.batch_alter_table('message_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_data_extra_data_type'))

    op.drop_table('message_data')
    with op.batch_alter_table('profile_custom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_custom_user_uuid'))
        batch_op.drop_index('idx_profile_custom_user_uuid')
        batch_op.drop_index('idx_profile_custom_updated_at')

    op.drop_table('profile_custom')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index('idx_participant_user_resource_type')
        batch_op.drop_index('idx_participant_user_resource')
        batch_op.drop_index('idx_participant_unique')
        batch_op.drop_index('idx_participant_resource_type_uuid')
        batch_op.drop_index('idx_participant_permissions', postgresql_using='gin')
        batch_op.drop_index('idx_participant_created_at')

    op.drop_table('participants')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_messages_chat_uuid'))
        batch_op.drop_index('idx_message_chat_created')

    op.drop_table('messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number_hash'))

    op.drop_table('users')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_hash'))

    op.drop_table('media')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index('idx_chats_type')

    op.drop_table('chats')
    # ### end Alembic commands ###